# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sigmoid_rcpp <- function(x) {
    .Call('varbvs_sigmoid_rcpp', PACKAGE = 'varbvs', x)
}

varbvsnormupdate_rcpp <- function(X, sigma, sa, logodds, xy, d, alpha, mu, Xr, i) {
    invisible(.Call('varbvs_varbvsnormupdate_rcpp', PACKAGE = 'varbvs', X, sigma, sa, logodds, xy, d, alpha, mu, Xr, i))
}

