# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Sigmoid function written with sugar.
#'
#' @param x A double.
#'
#' @author David Gerard
#'
sigmoidcpp <- function(x) {
    .Call('varbvs_sigmoidcpp', PACKAGE = 'varbvs', x)
}

#' Variational update of normal varbvs.
#'
#'
#' @param X An n by p matrix of predictors. The rows index the observations and the columns index the variables.
#' @param sigma A positive numeric. The residual variance.
#' @param sa A positive numeric. The prior variance.
#' @param logodds A p-vector that contains the prior log-odds of inclusion for each variable.
#' @param xy A p-vector containing \code{t(X) \%*\% y}, where \code{y} is a response vector.
#' @param d The diagonal of the Gram matrix, \code{d = diag(t(X) \%*\% X)}
#' @param alpha A p-vector of inclusion probabilities for each variable.
#' @param mu A p-vector of means for each coefficient.
#' @param Xr An n-vector with elements \code{X \%*\% (alpha * mu)}
#' @param i A p-vector of integers that give the order of updating the coefficients.
#'
#'
#' @export
#'
#' @author David Gerard
#'
varbvsnormupdate_cpp <- function(X, sigma, sa, logodds, xy, d, alpha, mu, Xr, i) {
    invisible(.Call('varbvs_varbvsnormupdate_cpp', PACKAGE = 'varbvs', X, sigma, sa, logodds, xy, d, alpha, mu, Xr, i))
}

