% Small script to compile the necessary MEX files.
mex -O -largeArrayDims CXX='g++44' CXXOPTIMFLAGS='-O3' ...
    LDOPTIMFLAGS='-O3' multisnpupdate.cpp doublevector.cpp ...
    singlematrix.cpp common.cpp
mex -O -largeArrayDims CXX='g++44' CXXOPTIMFLAGS='-O3' ...
    LDOPTIMFLAGS='-O3' multisnpbinupdate.cpp doublevector.cpp ...
    singlematrix.cpp common.cpp
mex -O -largeArrayDims CXX='g++44' CXXOPTIMFLAGS='-O3' ...
    LDOPTIMFLAGS='-O3' diagsqfast.cpp doublevector.cpp ...
    singlematrix.cpp common.cpp
mex -O -largeArrayDims CXX='g++44' CXXOPTIMFLAGS='-O3' ...
    LDOPTIMFLAGS='-O3' diagsqfast2.cpp doublevector.cpp ...
    singlematrix.cpp common.cpp
mex -O -largeArrayDims CXX='g++44' CXXOPTIMFLAGS='-O3' ...
    LDOPTIMFLAGS='-O3' var1fast.cpp doublevector.cpp ...
    singlematrix.cpp common.cpp
mex -O -largeArrayDims CXX='g++44' CXXOPTIMFLAGS='-O3' ...
    LDOPTIMFLAGS='-O3' maplogistic1d.cpp doublevector.cpp ...
    common.cpp

