% This is a small script to compile the necessary MEX files.
mex -O -largeArrayDims COPTIMFLAGS="-std=gnu99 -O3" LDOPTIMFLAGS="-O3" ...
    ../C/var1matlab.c ../C/doublevectormatlab.c ../C/singlematrixmatlab.c ...
    ../C/vectorops.c
mex -O -largeArrayDims COPTIMFLAGS="-std=gnu99 -O3" LDOPTIMFLAGS="-O3" ...
    ../C/diagsqmatlab.c ../C/diagsq.c ../C/doublevectormatlab.c ...
    ../C/singlematrixmatlab.c ../C/vectorops.c
% mex -O -largeArrayDims CXXOPTIMFLAGS='-O3' LDOPTIMFLAGS='-O3' ...
%     diagsqtfast.cpp doublevector.cpp singlematrix.cpp common.cpp
mex -O -largeArrayDims COPTIMFLAGS="-std=gnu99 -O3" LDOPTIMFLAGS="-O3" ...
    ../C/varbvsupdatematlab.c ../C/varbvs.c ../C/doublevectormatlab.c ...
    ../C/singlematrixmatlab.c ../C/vectorops.c ../C/sigmoid.c
% mex -O -largeArrayDims CXXOPTIMFLAGS='-O3' LDOPTIMFLAGS='-O3' ...
%     varbvsbinupdate.cpp doublevector.cpp singlematrix.cpp common.cpp
fprintf('Compilation of MEX files is complete.\n');
