% This is a small script to compile the necessary MEX files.
mex -O -largeArrayDims CXXOPTIMFLAGS='-O3' LDOPTIMFLAGS='-O3' ...
    var1fast.cpp doublevector.cpp singlematrix.cpp common.cpp
mex -O -largeArrayDims CXXOPTIMFLAGS='-O3' LDOPTIMFLAGS='-O3' ...
    diagsqfast.cpp doublevector.cpp singlematrix.cpp common.cpp
mex -O -largeArrayDims CXXOPTIMFLAGS='-O3' LDOPTIMFLAGS='-O3' ...
    diagsqtfast.cpp doublevector.cpp singlematrix.cpp common.cpp
mex -O -largeArrayDims CXXOPTIMFLAGS='-O3' LDOPTIMFLAGS='-O3' ...
    varbvsupdate.cpp doublevector.cpp singlematrix.cpp common.cpp
mex -O -largeArrayDims CXXOPTIMFLAGS='-O3' LDOPTIMFLAGS='-O3' ...
    varbvsbinupdate.cpp doublevector.cpp singlematrix.cpp common.cpp
fprintf('Compilcation of MEX files is complete.\n');
